version: '3.9'
services:

  nginx:
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - backendserver
    networks:
      - step250_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80

  frontendserver:
    build:
      context: ./front_step250/server
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_FRONT=${PORT_FRONT}
        - NAME_FRONT=${NAME_FRONT}
    env_file:
      - .env
    volumes:
      - ./front_step250:/home/appuser/devcon
    networks:
      - step250_network
    ports:
      - ${PORT_FRONT}:${PORT_FRONT}
    command: ["/bin/sh", "-c", "/home/appuser/devcon/build.sh"]

  backendserver:
    build: 
      context: ./back_step250/server
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_BACK=${PORT_BACK}
    volumes:
      - ./back_step250:/home/appuser/devcon
    networks:
      - step250_network
    # ports:
    #   - ${PORT_BACK}:${PORT_BACK}
    expose:
      - ${PORT_BACK}
    depends_on:
      - mysql
    command: ["/bin/sh", "-c", "/home/appuser/devcon/backend.sh"]

  mysql:
    build:
      context:  ./back_step250/mysql
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - step250_network
    volumes:
      - ./back_step250/mysql/data/db:/var/lib/mysql/${MYSQL_DATABASE}
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD      
      interval: 10s      
      timeout: 10s      
      retries: 3
      start_period: 30s
  
  phpmyadmin:
    image: phpmyadmin:5.1-apache
    env_file:
      - .env
    links:
      - mysql
    networks:
      - step250_network
    ports:
      - ${PORT_PMA}:80
    volumes:
        - ./back_step250/phpmyadmin/sessions:/sessions

networks:
  step250_network: